- name: Ensure UFW is installed
  apt: name=ufw state=present

- name: Set up firewall to allow SSH
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled

- name: Disable root SSH login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart ssh

- name: Enforce SSH key authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart ssh

- name: Restart ssh
  systemd:
    name: ssh
    state: restarted
